[package]
name = "error-proc-macros"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.96", features = [ "full", "extra-traits" ] }
